services:
  app:
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    command: >
      sh -c "
      php artisan key:generate --force &&
      php artisan migrate --force &&
      php artisan config:clear &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php-fpm
      "

  nginx:
    volumes:
      - ./public:/var/www/public:ro
